### PR TITLE
updated CLA url to jQuery's

### LINKED ISSUE #639: Update CONTRIBUTING.md to link to jQuery CLA
We should update that CONTRIBUTING.md to link to the jQuery CLA.  When the re-brand for the foundation arrives, we will likely need to update it again, but since the bot is checking contributions against the jQuery database anyways, we should ensure we point at the right CLA.

Refs #638.

### PR DESCRIPTION
**Pull request by sushantdhiman**
Hi

I have changed the CLA url from Dojo to jQuery's i.e. https://contribute.jquery.org/CLA/

Closes #639

### CODE REVIEW

**Comment by dylans** [comment]
Was this closed on purpose or by mistake?

**Comment by sushantdhiman** [comment]
No, I did it on purpose. I was waiting from 20 days now :)

**Comment by dylans** [comment]
Well, that seems a bit impatient honestly.

Yes, it's a trivial request, but we tend to batch review things that are not severe issues about once a month, rather than landing requests every day, as we prefer a workflow where we cluster similar work together.

**Comment by sushantdhiman** [comment]
> Well, that seems a bit impatient honestly.

Yes, Its correct. But please see my point of view as well, A new contributor wants to merge something so trivial that can be reviewed in less than 1 minute, has no response from two weeks.

Last PR was merged on 13 Apr (2 months ago). These facts disappoint me and makes me wonder if project is being maintained.

Sorry if I offended anyone in anyway, I never meant to. I just lost my enthusiasm to contribute after this wait.

**Comment by dylans** [comment]
We've been focused on working on a few larger additions to Intern which will often occur in a branch first, e.g. https://github.com/theintern/intern/tree/ranged_versions

We were still intending to land this and some other open PRs asap.

**Comment by sushantdhiman** [comment]
I wasn't aware about `ranged_versions` :)

But I have already deleted my fork so can't revive this one. I am really busy with sequelize but will try to reopen it whenever I get chance.

**Pull request closed without merging**
