### PR TITLE
Update istanbul to 0.4.1

### PR DESCRIPTION
**Pull request by JSMike**
As of istanbul 0.4.0 the LcovHtml reporter is updated with a new look and feel.

https://github.com/gotwarlost/istanbul/blob/master/CHANGELOG.md

The other changes since the current version of instanbul are minor and include bug fixes, bumping dependency versions, and adding additional es6 support.

I've tested out 0.4.1 on my local version of intern with local selenium / phantomjs reports with no issues.

### CODE REVIEW

**Comment by JSMike** [comment]
I'm not sure why this is failing Travis-CI, it's passing locally in PhantomJS

**Comment by JSMike** [comment]
I just created a browserstack acct to run selftest locally, and it ran successfully with no issues. I'm calling shenanigans! Closing/opening to get travis to retry.

**Comment by JSMike** [comment]
And success, so weird that it hung the first time.

**Comment by csnover** [comment]
Thanks!

**Pull request closed without merging**
