### PR TITLE
Fix Pretty.js test totals

### LINKED ISSUE #647: Pretty reporter shows incorrect total number of tests
When I run tests I see the following from the Pretty reporter:

```<br />Tunnel: Starting<br /><br />Total: [✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 75/51<br />Passed: 75  Failed: 0   Skipped: 0<br /><br />Phan 2 XP:  [✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 75/51<br />``` I have 51 functional tests and 24 unit tests so the total is 75, but the reporter thinks the total is 51.

### PR DESCRIPTION
**Pull request by gitgrimbo**
Add ClientSuite number of tests to grand total of tests.

Fixes #647.

### CODE REVIEW

**Comment by gitgrimbo** [comment]
I had already signed the Dojo CLA (as I have previously committed to Intern) but I think there is a name mismatch with my jQuery CLA submission.  I've tried resubmitting the CLA but it doesn't seen to have worked.  Can this be fixed?

Anyway, this is what my test output now looks like, so the totals are correct (for me):

````
tests\intern-selenium-grid
Tunnel: Starting

Total: [✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓×✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 624/624
Passed: 623  Failed: 1    Skipped: 0

Phan 2 XP:  [✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 78/78
Chr 51 XP:  [✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 78/78
Fx 46 WIN:  [✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 78/78
IE 11 WIN:  [✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓×✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 78/78, 1 fail
IE 9 WIN:   [✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 78/78
Fx 45 WIN:  [✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 78/78
IE 10 WIN:  [✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 78/78
Fx 31 WIN:  [✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 78/78
````

**Comment by dylans** [comment]
@gitgrimbo I fixed the CLA check manually for this commit. Your CLA is clearly on file so I'm not sure what the deal is (and it looks like you resubmitted it today as well)... let me know if you have this issue with any future PRs.

**Comment by gitgrimbo** [comment]
Great, thanks!

**Comment by gitgrimbo** [comment]
Hi, any progress on this?

**Comment by dylans** [comment]
@gitgimbro, had forgotten about it, will land this week probably...

**Comment by gitgrimbo** [comment]
Hi guys, any progress on this?  Is this a bug for anyone else or have I got an unusual setup?  I find myself having to patch this with each Intern 3.x version I install.  No idea if it's an issue for 4.x.

**Comment by jason0x43** [comment]
This has been merged in the 3.4 branch (https://github.com/theintern/intern/commit/7679fed6e015072f5383f1ee2e29c272bc01db93) and will go out in the next point release. Thanks!

**Pull request closed without merging**
