### PR TITLE
Add suiteError to TeamCity reporter

### PR DESCRIPTION
**Pull request by LingSpb**
This PR is supposed to fix the issue https://github.com/theintern/intern/issues/448

### CODE REVIEW

**Comment by csnover** [comment]
Hi,

It looks like you don’t have a signed CLA on file (or I can’t find it). Could you please sign the CLA at http://contribute.jquery.org/CLA/? It only needs to be done once, and thereafter you are able to contribute to any jQuery Foundation project.

Thanks!

**Comment by LingSpb** [comment]
I just did it. Could you check again? Thanks.

**Comment by csnover** [comment]
Received, thank you!

**Comment by csnover** [comment]
Thanks for the patch!

**Pull request closed without merging**
