### PR TITLE
Fix typo in benchmark example

### PR DESCRIPTION
**Pull request by rozaev**
You miss a `);` in the code example.

### CODE REVIEW

**Comment by rozaev** [comment]
@dylans are you alive?)

**Comment by dylans** [comment]
@rozaev, alive and well and another year older in fact. :) we'll land this now...

**Comment by rozaev** [comment]
@dylans congratulations! So, you can just close this too: https://github.com/theintern/intern/issues/705

PS: where I can find the intern community? I see nobody there: irc://irc.freenode.net/intern. I still have some questions but where I can ask them?

**Comment by dylans** [comment]
@rozaev I'm in there except when my irc client disconnects, and @jason0x43 is usually in there during his day. We've admittedly been very heads down on Intern 4 and Dojo 2, but feel free to ask. Or send us an email if we're not around at the same time of day as you.

**Comment by rozaev** [comment]
@dylans Well I didn't see your and @jason0x43 email at all. So, now I can't do this. Could you provide me an email? In our company we use dojo for development and intern for testing, so we are interested in cooperative. Maybe you could tell us about some best practices. We can try to participate in intern development and so on.

**Pull request merged**
