### PR TITLE
configure `options` before `config` in the grunt task

### PR DESCRIPTION
**Pull request by rhpijnacker**
Given the following grunt config:
>     {
>         intern: {
>             subset: {
>                 ...,
>                 config: '@subset'
>             },
>             configs: {
>                   subset: { ... }
>             }
>         }
>     }

When I select the `intern:subset` task, I see the `subset` configuration being configured first (as `config`) and the more general configuration next (as `options`). By doing this in this order, the more specific `subset` configuration is overwritten, which is not how it should be.

The rationale for setting it up like this: 
- We put the actual config in `intern.json` so we can still serve it with `intern serveOnly`
- We need the `configs` to select different configurations (e.g. subsets of tests that can and cannot be loaded with IE11)
- We initialize the intern configurations from a script that loads `intern.json` and adds e.g. the `config: '@subset'` property to select the right configuration for that task.

### CODE REVIEW

**Comment by jason0x43** [comment]
In general, the options specified in the Grunt config should take priority over the options specified in the base Intern config. Just out of curiosity, though, why does the sample Grunt config above declare it’s own ‘subset’ config?

**Comment by rhpijnacker** [comment]
| Just out of curiosity, though, why does the sample Grunt config above declare it’s own ‘subset’ config?

I'm trying to set things up such that we can easily run the tests from within a browser (during development) and also from our build scripts on a local selenium grid. Since not all tests run in IE11 (due to https://github.com/rhpijnacker/intern-cucumber/issues/10) we've split them up in batches (as per your suggestion). Doing so exposes some new issues, like this one and #894.

**Comment by rhpijnacker** [comment]
| In general, the options specified in the Grunt config should take priority over the options specified in the base Intern config. 

That's what I would expect too. However I'm not sure this is what I see happening now, since the config as specified via `intern:subtask` gets overwritten. How should I set up things so I can run the `subtask` as specified.

**Comment by jason0x43** [comment]
If your intern config defines child configs and grunt just needs to run one of those, it should only need to specify a 'config' option with the subtask name.

```
{
    intern: {
        subset: {
            config: '@subset'
        }
    }
}
```

Other values provided in the grunt config, such as it's own version of a child config, will overwrite values loaded from the base Intern config.

I haven't had a chance to look into this yet, but if grunt isn't able to properly load child a config from an Intern config, that's a problem.

> In general, the options specified in the Grunt config should take priority over the options specified in the base Intern config.

My comment here was just to point out that this PR effectively flips the priority of the config sources, making the Intern config file have priority over the options from Grunt.

**Pull request closed without merging**
