### PR TITLE
Improve HTML reporter #724

### PR DESCRIPTION
**Pull request by rozaev**
Hello @dylans, hello @jason0x43!

I decide to help with https://github.com/theintern/intern/issues/724 issue.

There is an initial pull request.

Known problems:

1. Icon for skipped tests is not exist. 
There is a `$skippedIcon` variable with `\e807` value in `intern/lib/reporters/html/variables.styl`, but fonts don't contain that character.

2. I don't know how link should look like.  Any ideas / markup / CSS class? 

3. Need to write functional tests for that path.

Now it's looks like this:
screenshot from 2017-09-25 20-13-23

### CODE REVIEW

**Comment by jason0x43** [comment]
Thanks for your interest! Could you rework this against the master branch? (The changes should be pretty similar there.) We'd prefer to put new features in the Intern 4 code, at least for now.

**Comment by jason0x43** [comment]
As far as the link styling goes, we can leave that at the default for now.

**Comment by rozaev** [comment]
Okay, now this pull request against master branch.

There are also another problem: I use ` window.location` in my patch, but it is not exist in nodejs environment. How I can check in which environment I am?

**Comment by rozaev** [comment]
Rework against master branch: https://github.com/theintern/intern/pull/802

**Pull request closed without merging**
