### PR TITLE
Fix circular references

### PR DESCRIPTION
**Pull request by rhpijnacker**
Fixes situations where an AssertionError is sent that contains circular references.

### CODE REVIEW

**Comment by jason0x43** [comment]
What about expanding the [stringify](https://github.com/theintern/intern/blob/master/src/lib/common/util.ts#L837) function in `common/lib/util` to handle Errors and then using it?

**Comment by rhpijnacker** [comment]
As suggested on Gitter, reworked it to a more generic solution, using [this MDN snippet](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value#circular_references) as the basis.

**Comment by jason0x43** [comment]
Please retarget the PR against master (the monorepo conversion was put on hold, and dev switched back to that). Also, we'll probably need to import a core-js shim (`src/lib/browser/shim.ts`) for WeakMap since IE doesn't support that.

**Comment by rhpijnacker** [comment]
Replaced with #1188 .

**Pull request closed without merging**
