### PR TITLE
Cucumber support

### PR DESCRIPTION
**Pull request by jason0x43**
This PR integrates the [Cucumber.js](https://github.com/cucumber/cucumber-js) test runner into Intern to allow tests to be written in Gherkin syntax. See #81.

### CODE REVIEW

**Comment by pknepper** [comment]
When will this PR become part of an official release?

**Comment by richardruiter** [comment]
When is this going to be merged? :+1: it is really awesome!

**Comment by csnover** [comment]
Hi @pknepper and @richardruiter, this branch is under review to be landed but is lower priority than some of our other work. Our plan was to try to get this feature landed for the next major release, but we have had some shift in priority so it may actually end up in the n+1 release. If you want a guarantee that the feature will be introduced in the next release you may sponsor the work to get it finished more quickly. Otherwise, just watch this ticket and you will be the first to know when it’s landed. Thanks for your interest!

**Comment by richardruiter** [comment]
What do you mean with sponsor the work?

**Comment by csnover** [comment]
@richardruiter I mean SitePen is a consulting company, so if you’d like, you can hire us and we will convert your money into new features. :)

**Comment by jason0x43** [comment]
This PR will be replaced with a new implementation after the [refactor-execution](https://github.com/theintern/intern/tree/refactor-execution) branch is finished.

**Comment by SirLenz0rlot** [comment]
The latest link to refactor-execution is dead, I wondered if there are any updates on the status/planning of the integration with cucumber?

**Pull request closed without merging**
